import { cn } from '@/lib/utils'
import './globals.css'
import { karla, prompt } from './fonts'
import Providers from '@/components/features/providers/providers'
import Header from '@/components/features/header/header'
import Footer from '@/components/footer/footer'
export const metadata = {
  title: 'Dizajer Page',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={cn(
          karla.variable,
          prompt.variable,
          'text-foreground font-sans flex bg-dizajer-black justify-center'
        )}
      >
        <Providers>
          <div className='flex flex-col container w-[1440px] bg-dizajer-black text-white'>
            <Header />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
